name: PortalProduction Deployment

# Trigger on main branch push
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0 # Stable Node.js version

      # Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      # Clear cache and install dependencies
      - name: Install Dependencies
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps

      # Pull Vercel environment
      - name: Vercel Environment Pull
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Build project
      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}